---
- name: Получение IP-адреса клиента
  command: hostname -I
  register: ip_address_output

- name: Настройка DNS
  command: nmcli connection modify Wired\ connection\ 1 ipv4.dns {{ dns }} ipv4.dns-search {{ domain_search }}

- name: Перезапуск NetworkManager
  service:
    name: NetworkManager
    state: restarted

- name: Изменение hostname 
  command: hostnamectl set-hostname wrka-01-01.{{ domain_search }}
  when: ip_address_output.stdout.split(' ')[0] == "10.0.117.119"

- name: Обновление списка пакетов
  apt:
    update_cache: yes

- name: Установка пакетов, необходимых для присоединения к домену
  apt: 
    name: astra-ad-sssd-client
    state: present

- name: Присоединение к домену Active Directory 
  command: astra-ad-sssd-client -d {{ domain_name }} -u {{ domain_admin }} -p {{ domain_admin_password }} -y

- name: Перезагрузка системы
  command: reboot
  async: 1
  poll: 0
  ignore_errors: true