---
- name: Сетевая настройка
  command: nmcli connection modify "Wired connection 1" connection.autoconnect yes ipv4.addresses {{ ip4 }}/{{ netmask }} ipv4.gateway {{ gateway }} ipv4.method {{ ipv4_method }} ipv4.dns {{ dns }} ipv4.dns-search {{ domain_search }} 

- name: Изменение hostname 
  command: hostnamectl set-hostname {{ new_hostname }}.{{ domain_search }}

- name: Перезапуск NetworkManager
  service:
    name: NetworkManager
    state: restarted

- name: Отключение сетевого интерфейса
  command: nmcli connection down "Wired connection 1"

- name: Включение сетевого интерфейса
  command: nmcli connection up "Wired connection 1"

- name: Включение стандартных репозиториев Astra Linux
  copy:
    content: |
      deb https://download.astralinux.ru/astra/stable/1.7_x86-64/repository-main/ 1.7_x86-64 main contrib non-free
      deb https://download.astralinux.ru/astra/stable/1.7_x86-64/repository-update/ 1.7_x86-64 main contrib non-free
      deb https://download.astralinux.ru/astra/stable/1.7_x86-64/repository-base/ 1.7_x86-64 main contrib non-free
      deb https://download.astralinux.ru/astra/stable/1.7_x86-64/repository-extended/ 1.7_x86-64 main contrib non-free
    dest: /etc/apt/sources.list
  when: need_repositories

- name: Обновление списка пакетов
  apt:
    update_cache: yes

- name: Установка пакетов, необходимых для присоединения к домену
  apt: 
    name: astra-ad-sssd-client
    state: present

- name: Присоединение к домену Active Directory 
  command: astra-ad-sssd-client -d {{ domain_name }} -u {{ domain_admin }} -p {{ domain_admin_password }} -y

- name: Успешный вход в домен {{ domain_name }}
  debug:
    msg: "Необходимо перезагрузить ПК!"