---
- name: Сетевая настройка
  command: nmcli connection modify "Wired connection 1" ipv4.addresses {{ new_ip }}/{{ netmask }} ipv4.gateway {{ gateway }} ipv4.method {{ ipv4_method }} ipv4.dns {{ dns }} ipv4.dns-search {{ domain_search }} 

- name: Изменение hostname 
  command: hostnamectl set-hostname {{ new_hostname }}.{{ domain_search }}

- name: Перезапуск NetworkManager
  service:
    name: NetworkManager
    state: restarted

- name: Обновление списка пакетов
  apt:
    update_cache: yes

- name: Установка пакетов, необходимых для присоединения к домену
  apt: 
    name: astra-ad-sssd-client
    state: present

- name: Присоединение к домену Active Directory 
  command: astra-ad-sssd-client -d {{ domain_name }} -u {{ domain_admin }} -p {{ domain_admin_password }} -y

- name: Успешный вход в домен {{ domain_name }}
  debug:
    msg: "Необходимо перезагрузить ПК!"