##################################
ip4: "123"
netmask: "123"
gateway: "123"
dns: "123"
domain_search: "asd"
domain_admin: "asd"
domain_admin_password: "asd"
new_hostname: "asd"

##################################
change_stable_repositories: true
change_frozen_repositories: true
change_network: true
change_hostname: true
change_domain: true
change_wallpaper_background: true
change_wallpaper: true
