##################################
ip4: "123123"
netmask: "123123"
gateway: "123123"
dns: "123123123"
domain_search: "123123"
domain_admin: "3123123"
domain_admin_password: "1212312312312"
new_hostname: "12312"

##################################
change_stable_repositories: true
change_frozen_repositories: true
change_network: true
change_hostname: true
change_domain: true
change_wallpaper_background: true
change_wallpaper: true
