---
- name: Установка пакета autofs
  apt:
      name: autofs
      state: present
  
- name: Настройка autofs /etc/auto.master
  lineinfile:
    path: /etc/auto.master
    line: "/media/yakutia /etc/yakutia.cifs --ghost"
    insertafter: EOF

- name: Создание и редактирование /etc/yakutia.cifs
  copy:
    content: "{{ item }}"
    dest: /etc/yakutia.cifs
  loop:
    - "{{ name_network_folder_1 }} -fstype=cifs,multiuser,cruid=$UID,sec=krb5,file_mode=0777,dir_mode=0777,iocharset=utf8,domain={{ domain_name }},nofail ://{{ server_hostname_network_folder }}/{{ name_network_folder_1 }}"
    - "{{ name_network_folder_2 }} -fstype=cifs,multiuser,cruid=$UID,sec=krb5,file_mode=0777,dir_mode=0777,iocharset=utf8,domain={{ domain_name }},nofail ://{{ server_hostname_network_folder }}/{{ name_network_folder_2 }}"


- name: Создание папки /media/yakutia
  file:
    path: /media/yakutia
    state: directory

- name: Перезагрузка службы autofs
  systemd:
    name: autofs
    state: restarted