# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\test.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1012, 599)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(".\\logo_window_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Nirmala UI Semilight")
        self.centralwidget.setFont(font)
        self.centralwidget.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.MainBackground = QtWidgets.QLabel(self.centralwidget)
        self.MainBackground.setGeometry(QtCore.QRect(0, 0, 1071, 601))
        self.MainBackground.setStyleSheet("QLabel#MainBackground {\n"
"    background: qlineargradient(spread:reflect, x1:0, y1:1, x2:0, y2:0, stop:0 rgba(94, 2, 1, 255), stop:0.85 rgba(6, 0, 156, 255))\n"
"};")
        self.MainBackground.setText("")
        self.MainBackground.setObjectName("MainBackground")
        self.OpacityBackground_2 = QtWidgets.QLabel(self.centralwidget)
        self.OpacityBackground_2.setGeometry(QtCore.QRect(10, 10, 331, 581))
        self.OpacityBackground_2.setStyleSheet("QLabel#OpacityBackground_2 {\n"
"    background: rgba(255,255,255,0.35);\n"
"    border-radius: 20px;\n"
"};")
        self.OpacityBackground_2.setText("")
        self.OpacityBackground_2.setObjectName("OpacityBackground_2")
        self.AnsiblePlaybook_Button = QtWidgets.QPushButton(self.centralwidget)
        self.AnsiblePlaybook_Button.setGeometry(QtCore.QRect(20, 110, 311, 61))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.AnsiblePlaybook_Button.setFont(font)
        self.AnsiblePlaybook_Button.setStyleSheet("QPushButton#AnsiblePlaybook_Button {\n"
"    border: 2px solid #333; /* Цвет рамки */\n"
"    border-radius: 5px; /* Скругление углов */\n"
"    padding: 5px 10px; /* Внутренний отступ */\n"
"    background-color: #fff; /* Цвет фона */\n"
"}\n"
"\n"
"QPushButton#AnsiblePlaybook_Button:hover {\n"
"    background-color: #444; /* Цвет фона при наведении */\n"
"    color: #fff; /* Цвет текста при наведении */\n"
"}\n"
"\n"
"QPushButton#AnsiblePlaybook_Button:pressed {\n"
" background-color: #666; /* Цвет фона при нажатии */\n"
"    color: #fff; /* Цвет текста при нажатии */\n"
"}")
        self.AnsiblePlaybook_Button.setAutoDefault(False)
        self.AnsiblePlaybook_Button.setObjectName("AnsiblePlaybook_Button")
        self.AnsibleScroll_Area = QtWidgets.QScrollArea(self.centralwidget)
        self.AnsibleScroll_Area.setGeometry(QtCore.QRect(350, 10, 651, 581))
        self.AnsibleScroll_Area.setStyleSheet("border-radius: 20px;\n"
"background: rgba(0,0,0,0.2);")
        self.AnsibleScroll_Area.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.AnsibleScroll_Area.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.AnsibleScroll_Area.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.AnsibleScroll_Area.setWidgetResizable(True)
        self.AnsibleScroll_Area.setObjectName("AnsibleScroll_Area")
        self.AnsibleContent = QtWidgets.QWidget()
        self.AnsibleContent.setGeometry(QtCore.QRect(0, 0, 634, 1000))
        self.AnsibleContent.setMinimumSize(QtCore.QSize(0, 1000))
        font = QtGui.QFont()
        font.setFamily("Niagara Engraved")
        self.AnsibleContent.setFont(font)
        self.AnsibleContent.setStyleSheet("")
        self.AnsibleContent.setObjectName("AnsibleContent")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.AnsibleContent)
        self.verticalLayout.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Ansible_network_and_domain = QtWidgets.QFrame(self.AnsibleContent)
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        self.Ansible_network_and_domain.setFont(font)
        self.Ansible_network_and_domain.setStyleSheet("QFrame#Ansible_network_and_domain {\n"
"    background: rgba(255,255,255,0.2);\n"
"    border-radius: 20px;\n"
"}")
        self.Ansible_network_and_domain.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Ansible_network_and_domain.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Ansible_network_and_domain.setObjectName("Ansible_network_and_domain")
        self.network_and_domain_frame = QtWidgets.QFrame(self.Ansible_network_and_domain)
        self.network_and_domain_frame.setGeometry(QtCore.QRect(10, 10, 311, 301))
        self.network_and_domain_frame.setStyleSheet("QFrame#network_and_domain_frame {\n"
"    background: rgba(255,255,255,1);\n"
"}\n"
"\n"
"\n"
"QFrame > QLineEdit {\n"
"    border: 1px solid #333;\n"
"    background-color: #fff;\n"
"}\n"
"")
        self.network_and_domain_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.network_and_domain_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.network_and_domain_frame.setObjectName("network_and_domain_frame")
        self.IP = QtWidgets.QLineEdit(self.network_and_domain_frame)
        self.IP.setGeometry(QtCore.QRect(10, 40, 291, 25))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(13)
        self.IP.setFont(font)
        self.IP.setText("")
        self.IP.setClearButtonEnabled(True)
        self.IP.setObjectName("IP")
        self.Netmask = QtWidgets.QLineEdit(self.network_and_domain_frame)
        self.Netmask.setGeometry(QtCore.QRect(10, 70, 291, 25))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(13)
        self.Netmask.setFont(font)
        self.Netmask.setClearButtonEnabled(True)
        self.Netmask.setObjectName("Netmask")
        self.Gateway = QtWidgets.QLineEdit(self.network_and_domain_frame)
        self.Gateway.setGeometry(QtCore.QRect(10, 100, 291, 25))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(13)
        self.Gateway.setFont(font)
        self.Gateway.setClearButtonEnabled(True)
        self.Gateway.setObjectName("Gateway")
        self.DNS = QtWidgets.QLineEdit(self.network_and_domain_frame)
        self.DNS.setGeometry(QtCore.QRect(10, 130, 291, 25))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(13)
        self.DNS.setFont(font)
        self.DNS.setClearButtonEnabled(True)
        self.DNS.setObjectName("DNS")
        self.SearchDomain = QtWidgets.QLineEdit(self.network_and_domain_frame)
        self.SearchDomain.setGeometry(QtCore.QRect(10, 160, 291, 25))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(13)
        self.SearchDomain.setFont(font)
        self.SearchDomain.setClearButtonEnabled(True)
        self.SearchDomain.setObjectName("SearchDomain")
        self.Hostname = QtWidgets.QLineEdit(self.network_and_domain_frame)
        self.Hostname.setGeometry(QtCore.QRect(10, 190, 291, 25))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(13)
        self.Hostname.setFont(font)
        self.Hostname.setClearButtonEnabled(True)
        self.Hostname.setObjectName("Hostname")
        self.LoginAdmin = QtWidgets.QLineEdit(self.network_and_domain_frame)
        self.LoginAdmin.setGeometry(QtCore.QRect(10, 220, 291, 25))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(13)
        self.LoginAdmin.setFont(font)
        self.LoginAdmin.setClearButtonEnabled(True)
        self.LoginAdmin.setObjectName("LoginAdmin")
        self.PasswordAdmin = QtWidgets.QLineEdit(self.network_and_domain_frame)
        self.PasswordAdmin.setGeometry(QtCore.QRect(10, 250, 291, 25))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(13)
        self.PasswordAdmin.setFont(font)
        self.PasswordAdmin.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.PasswordAdmin.setClearButtonEnabled(True)
        self.PasswordAdmin.setObjectName("PasswordAdmin")
        self.network_and_domain_frame_title = QtWidgets.QLabel(self.network_and_domain_frame)
        self.network_and_domain_frame_title.setGeometry(QtCore.QRect(60, 5, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(False)
        self.network_and_domain_frame_title.setFont(font)
        self.network_and_domain_frame_title.setStyleSheet("QLabel#network_and_domain_frame_title {\n"
"    background: transparent;\n"
"}")
        self.network_and_domain_frame_title.setAlignment(QtCore.Qt.AlignCenter)
        self.network_and_domain_frame_title.setObjectName("network_and_domain_frame_title")
        self.verticalLayout.addWidget(self.Ansible_network_and_domain)
        self.Ansible_network_folders = QtWidgets.QFrame(self.AnsibleContent)
        self.Ansible_network_folders.setStyleSheet("background: rgba(255,255,255,0.35);\n"
"border-radius: 20px;")
        self.Ansible_network_folders.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Ansible_network_folders.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Ansible_network_folders.setObjectName("Ansible_network_folders")
        self.verticalLayout.addWidget(self.Ansible_network_folders)
        self.frame = QtWidgets.QFrame(self.AnsibleContent)
        self.frame.setStyleSheet("background: rgba(255,255,255,0.35);\n"
"border-radius: 20px;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout.addWidget(self.frame)
        self.AnsibleScroll_Area.setWidget(self.AnsibleContent)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.AnsiblePlaybook_Button, self.AnsibleScroll_Area)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "АйтекИнфо"))
        self.AnsiblePlaybook_Button.setText(_translate("MainWindow", "Ansible Playbook\'и"))
        self.IP.setPlaceholderText(_translate("MainWindow", "IP-адрес"))
        self.Netmask.setPlaceholderText(_translate("MainWindow", "Маска подсети (в виде 24)"))
        self.Gateway.setPlaceholderText(_translate("MainWindow", "Шлюз"))
        self.DNS.setPlaceholderText(_translate("MainWindow", "IP-адрес DNS"))
        self.SearchDomain.setPlaceholderText(_translate("MainWindow", "Поисковый домен"))
        self.Hostname.setPlaceholderText(_translate("MainWindow", "Новый hostname для хоста"))
        self.LoginAdmin.setPlaceholderText(_translate("MainWindow", "Логин доменного админа"))
        self.PasswordAdmin.setPlaceholderText(_translate("MainWindow", "Пароль доменного админа"))
        self.network_and_domain_frame_title.setText(_translate("MainWindow", "Введите данные"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
