# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\test.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1059, 597)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(".\\logo_window_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.centralwidget.setObjectName("centralwidget")
        self.MainBackground = QtWidgets.QLabel(self.centralwidget)
        self.MainBackground.setGeometry(QtCore.QRect(0, 0, 1071, 601))
        self.MainBackground.setStyleSheet("QLabel#MainBackground {\n"
"    background: qlineargradient(spread:reflect, x1:0, y1:1, x2:0, y2:0, stop:0 rgba(94, 2, 1, 255), stop:0.85 rgba(6, 0, 156, 255))\n"
"};")
        self.MainBackground.setText("")
        self.MainBackground.setObjectName("MainBackground")
        self.OpacityBackground = QtWidgets.QLabel(self.centralwidget)
        self.OpacityBackground.setGeometry(QtCore.QRect(350, 10, 701, 581))
        self.OpacityBackground.setStyleSheet("QLabel#OpacityBackground {\n"
"    background: rgba(255,255,255,0.35);\n"
"    border-radius: 20px;\n"
"};")
        self.OpacityBackground.setText("")
        self.OpacityBackground.setObjectName("OpacityBackground")
        self.OpacityBackground_2 = QtWidgets.QLabel(self.centralwidget)
        self.OpacityBackground_2.setGeometry(QtCore.QRect(10, 10, 331, 581))
        self.OpacityBackground_2.setStyleSheet("QLabel#OpacityBackground_2 {\n"
"    background: rgba(255,255,255,0.35);\n"
"    border-radius: 20px;\n"
"};")
        self.OpacityBackground_2.setText("")
        self.OpacityBackground_2.setObjectName("OpacityBackground_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(30, 190, 311, 41))
        self.pushButton.setObjectName("pushButton")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(350, 10, 701, 581))
        self.scrollArea.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1218, 618))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame.setMinimumSize(QtCore.QSize(1200, 600))
        self.frame.setStyleSheet("background-color: rgb(170, 255, 0);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(30, 30, 421, 451))
        self.label.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.frame)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.MainBackground.raise_()
        self.OpacityBackground_2.raise_()
        self.OpacityBackground.raise_()
        self.pushButton.raise_()
        self.scrollArea.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "АйтекИнфо"))
        self.pushButton.setText(_translate("MainWindow", "PushButton"))
        self.label.setText(_translate("MainWindow", "TextLabel"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
