# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1061, 600)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("logo_window_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.centralwidget.setObjectName("centralwidget")
        self.MainBackground = QtWidgets.QLabel(self.centralwidget)
        self.MainBackground.setGeometry(QtCore.QRect(0, 0, 1071, 601))
        self.MainBackground.setStyleSheet("QLabel#MainBackground {\n"
"    background: qlineargradient(spread:reflect, x1:0, y1:1, x2:0, y2:0, stop:0 rgba(94, 2, 1, 255), stop:0.85 rgba(6, 0, 156, 255))\n"
"};")
        self.MainBackground.setText("")
        self.MainBackground.setObjectName("MainBackground")
        self.OpacityBackground = QtWidgets.QLabel(self.centralwidget)
        self.OpacityBackground.setGeometry(QtCore.QRect(10, 10, 1041, 581))
        self.OpacityBackground.setStyleSheet("QLabel#OpacityBackground {\n"
"    background: rgba(255,255,255,0.35);\n"
"    border-radius: 20px;\n"
"};")
        self.OpacityBackground.setText("")
        self.OpacityBackground.setObjectName("OpacityBackground")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "АйтекИнфо"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
